# This file goes in the root of your project
# It tells Netlify how to build and deploy your site

[dev]
  command = "vite"
  targetPort = 5173
  functions = "netlify/functions"

[build]
  # This is the command to build your React app
  command = "npm run build"
  # This is the directory that contains your built site
  publish = "dist"
  # This is where Netlify will find your serverless functions
  functions = "netlify/functions"

# This rule redirects any requests from your app to /api/*
# to the corresponding serverless function.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[edge_functions]
